### ISSUE TITLE
Change primary key to UID

### ISSUE THREAD

**Issue by fwiethof** [terraform-providers/terraform-provider-fortios#21] opened 2019-07-02 12:03 UTC
As seen in #20, using the object name as the primary key is not suitable.

I suggest you use the UID as the primary key.
When calling the API, you need to use the object name.
You can query all objects, filter for the UID and receive one result (or none), which you can then use to get the UID/name mapping.

Using the UID will enable renames.

**Comment by frankshen01** [comment] 2019-07-02 12:18
Hi, @fwiethof , thank you for your suggestion. I am thinking about this problem. Which UUID are you talking about? the UUID automatically generated by the go/Terraform function library, or the UUID of the resource on the device returned by the API?

**Comment by fwiethof** [comment] 2019-07-02 12:20
I mean the marked UUID:
![image](https://user-images.githubusercontent.com/1589973/60512287-7b786b80-9cd4-11e9-87de-5bb665a7c95e.png)

**Comment by frankshen01** [comment] 2019-07-02 12:41
For address, address group, vip, vip group, security policy objects, the solution is feasible. But for IP pool, Service, Service Group, etc., their names can be modified, but API will not return UUID , the solution will be not feasible.

From the perspective of overall software architecture development, the solution will lead to that the name modification for different resources will require different methods, as the system continues to grow, I think this will lead to the software system confusion and difficulty maintaining, so I am thinking about a more reasonable and reliable solution.

**Comment by fwiethof** [comment] 2019-07-02 12:44
I understand what you say. However, not being able to rename is a major issue.
You need to judge what is more important.

**Comment by frankshen01** [comment] 2019-07-02 13:30
Hi,  @fwiethof , yes, the problem is important, sorry to bring you trouble. Since the IP pool, Service, Service Group, etc. name modification problem cannot be solved yet, at present, it really takes some time to solve this problem. 

We are evaluating and trying several options and have not yet fully determined. 

And I will fix it with a compromised branch first for those urgent use. Thank you very much for your very helpful and constructive comments, which we indeed appreciated. Your suggestion is always welcome!

**Comment by frankshen01** [comment] 2019-07-05 08:31
Hey @fwiethof, thanks for opening this issue. The name modification feature has been supported in https://github.com/terraform-providers/terraform-provider-fortios/tree/ti-namemodify-import. It should make it into the next release.

**Comment by fwiethof** [comment] 2019-07-07 13:54
hi @frankshen01 we will test and give feedback soon

**Comment by fwiethof** [comment] 2019-07-08 20:41
@frankshen01 I have successfully tested renaming address objects.
I saw you still use the name as the ID, but change the ID in the state upon name change.
I'm not into Terraform internals, but from my point of view this looks like a nice solution.
I'll keep you updated for more object types as we progress migrating our configs.

**Comment by gaozb01** [comment] 2019-10-21 08:37
Close the issue as the master branch already includes the fix.

Hi @fwiethof , please feel free to reopen it if you still encounter the same issue in the future. thanks.

**Closed by gaozb01** 2019-10-21 08:37 UTC
